# Generated by Django 5.2.8 on 2025-11-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRAND_NAME', models.CharField(max_length=100)),
                ('BRAND_COUNTRY', models.CharField(max_length=100)),
                ('BRAND_RATING', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_NAME', models.CharField(max_length=100)),
                ('CAR_MODEL', models.CharField(max_length=100)),
                ('CAR_PRICE', models.FloatField()),
                ('CAR_BRAND', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='duikt_task_mykhailov.carsbrand')),
            ],
        ),
    ]
